[package]
name = "run"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.0.9"
fs-err = "2.7.0"

[dev-dependencies]
async-trait = "0.1"
cucumber = "0.13"
futures = "0.3"
rand = "0.8.5"
pretty = { package = "pretty_assertions", version = "1.2.1" }

[[test]]
name = "cucumber" # this should be the same as the filename of your test target
harness = false  # allows Cucumber to print output instead of libtest
